# Generated by Django 4.0.3 on 2022-03-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_coffee_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
    ]
